"""initial schema

Revision ID: 7b696e38b8c3
Revises: 
Create Date: 2026-08-04 09:40:53.689288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b696e38b8c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_code'), 'branches', ['code'], unique=True)
    op.create_table('membership_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('promotion_code', sa.String(length=40), nullable=False),
    sa.Column('promotion_name', sa.String(length=120), nullable=False),
    sa.Column('base_duration_value', sa.Integer(), nullable=False),
    sa.Column('base_duration_unit', sa.String(length=10), nullable=False),
    sa.Column('extra_duration_value', sa.Integer(), nullable=False),
    sa.Column('extra_duration_unit', sa.String(length=10), nullable=False),
    sa.Column('package_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('applicable_membership_type', sa.String(length=120), nullable=True),
    sa.Column('usage_limit', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Inactive', 'Expired', name='promotionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promotion_code')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('Branch Manager', 'Head Office', 'CEO', name='userrole', native_enum=False, length=30), nullable=False),
    sa.Column('branch', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('walkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('time', sa.String(length=40), nullable=True),
    sa.Column('purpose', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('membership_type', sa.String(length=40), nullable=False),
    sa.Column('join_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('days_left', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Pending for Approval', 'Expire', 'Renewing', name='memberstatus', native_enum=False, length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('branch', sa.String(length=120), nullable=True),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('promotion_applied', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_branch'), 'members', ['branch'], unique=False)
    op.create_index(op.f('ix_members_member_code'), 'members', ['member_code'], unique=True)
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('request_type', sa.String(length=40), nullable=False),
    sa.Column('membership_type', sa.String(length=40), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('branch', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('Pending for Approval', 'Approved', 'Rejected', name='approvalstatus', native_enum=False, length=30), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('promotion_applied', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_branch'), 'approvals', ['branch'], unique=False)
    op.create_index(op.f('ix_approvals_status'), 'approvals', ['status'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('member_code', sa.String(length=20), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('branch', sa.String(length=120), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_branch'), 'checkins', ['branch'], unique=False)
    op.create_index(op.f('ix_checkins_scanned_at'), 'checkins', ['scanned_at'], unique=False)
    op.create_table('renewals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('member_code', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=True),
    sa.Column('processed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('Renewing', 'Approved', name='renewalstatus', native_enum=False, length=20), nullable=False),
    sa.Column('bonus_days', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('previous_end_date', sa.Date(), nullable=True),
    sa.Column('new_end_date', sa.Date(), nullable=True),
    sa.Column('promotion_applied', sa.Text(), nullable=True),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('membership_type', sa.String(length=40), nullable=True),
    sa.Column('approved_by', sa.String(length=120), nullable=True),
    sa.Column('branch', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_renewals_branch'), 'renewals', ['branch'], unique=False)
    op.create_index(op.f('ix_renewals_member_id'), 'renewals', ['member_id'], unique=False)
    op.create_index(op.f('ix_renewals_status'), 'renewals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_renewals_status'), table_name='renewals')
    op.drop_index(op.f('ix_renewals_member_id'), table_name='renewals')
    op.drop_index(op.f('ix_renewals_branch'), table_name='renewals')
    op.drop_table('renewals')
    op.drop_index(op.f('ix_checkins_scanned_at'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_branch'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_approvals_status'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_branch'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.drop_index(op.f('ix_members_member_code'), table_name='members')
    op.drop_index(op.f('ix_members_branch'), table_name='members')
    op.drop_table('members')
    op.drop_table('walkins')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('reports')
    op.drop_table('promotions')
    op.drop_table('membership_types')
    op.drop_index(op.f('ix_branches_code'), table_name='branches')
    op.drop_table('branches')
    # ### end Alembic commands ###
